apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-mluv
  namespace: jvm-build-nkvu
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: jvm-build-suite-application-qfoa
        appstudio.openshift.io/component: jvm-build-suite-component-mluv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: jvm-build-suite-component-mluv-
      labels:
        appstudio.openshift.io/application: jvm-build-suite-application-qfoa
        appstudio.openshift.io/component: jvm-build-suite-component-mluv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: jvm-build-nkvu
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/hacbs-test-project
      - name: output-image
        value: quay.io/psturc/test-images:7f8a9485461a43fb9e5b76c27892984f-$(tt.params.git-revision)
      - name: revision
        value: main
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: java-builder
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
